spring.application.name=AIResumeAnalyzer-1
spring.datasource.url=jdbc:mysql://localhost:3306/airesumeanalyzer
spring.datasource.username=root
spring.datasource.password=Vika#123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.boot=DEBUG